#if !canImport(ObjectiveC)
import XCTest

extension ClassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClassTests = [
        ("test_internal_Swift_class", test_internal_Swift_class),
        ("test_local_Swift_class", test_local_Swift_class),
        ("test_private_Swift_class", test_private_Swift_class),
        ("test_public_Swift_class", test_public_Swift_class),
    ]
}

extension Edgcases {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Edgcases = [
        ("test_CocoaError", test_CocoaError),
        ("test_derived_annotated_NSError", test_derived_annotated_NSError),
        ("test_derived_NSError", test_derived_NSError),
        ("test_derived_underlying_NSError", test_derived_underlying_NSError),
        ("test_vanilla_NSError", test_vanilla_NSError),
    ]
}

extension EnumTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumTests = [
        ("test_internal_Swift_enum", test_internal_Swift_enum),
        ("test_local_Swift_enum", test_local_Swift_enum),
        ("test_private_Swift_enum", test_private_Swift_enum),
        ("test_public_Swift_enum", test_public_Swift_enum),
        ("test_Swift_LocalizedError_enum_with_errorDescription", test_Swift_LocalizedError_enum_with_errorDescription),
        ("test_Swift_LocalizedError_enum_without_errorDescription", test_Swift_LocalizedError_enum_without_errorDescription),
    ]
}

extension StructTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StructTest = [
        ("test_internal_Swift_struct", test_internal_Swift_struct),
        ("test_local_Swift_struct", test_local_Swift_struct),
        ("test_private_Swift_enum", test_private_Swift_enum),
        ("test_public_Swift_struct", test_public_Swift_struct),
        ("test_Swift_LocalizedError_struct_with_errorDescription", test_Swift_LocalizedError_struct_with_errorDescription),
        ("test_Swift_LocalizedError_struct_without_errorDescription", test_Swift_LocalizedError_struct_without_errorDescription),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ClassTests.__allTests__ClassTests),
        testCase(Edgcases.__allTests__Edgcases),
        testCase(EnumTests.__allTests__EnumTests),
        testCase(StructTest.__allTests__StructTest),
    ]
}
#endif
